apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: go-gin
  name: go-gin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-gin
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-gin
    spec:
      containers:
      - image: yoichi00/container-ren:go-gin
        name: go-gin
        env:
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: common-env
              key: MARIADB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: common-env
              key: MARIADB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: common-env
              key: MARIADB_DATABASE
        # - name: DB_HOST
        #  value: management-db
        resources: {}
status: {}
