apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: node-react
  name: node-react
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: node-react
  type: NodePort
status:
  loadBalancer: {}
