apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: go-gin
  name: go-gin
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: go-gin
  type: NodePort
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: management-api
  name: management-api
spec:
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: go-gin
  type: ClusterIP
status:
  loadBalancer: {}
